# Generated by Django 6.1.1 on 2026-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbuxTvLmcRQ0jT24UR5jTxeYkxOyjfy4ylH_Yx-pmEKw&s=10', max_length=500),
        ),
    ]
